### ISSUE TITLE
Garbage Collection Not Executing During asyncio.sleep(0)

### ISSUE THREAD

**Issue by FinnWBiggs** [adafruit/Adafruit_CircuitPython_asyncio#39]
When running the minimal leak example as main.py, gc.mem_free() presents 32 bytes fewer available this iteration.

[MinLeakExample.txt](https://github.com/adafruit/Adafruit_CircuitPython_asyncio/files/10680364/MinLeakExample.txt)

Can be mitigated by calling code with frequent gc.collect() as a stopgap.

**Comment by dhalbert** [comment]
I saw this on discord. There is not a leak, but there is consumed storage on each loop. It's not a leak because `gc.collect()` will collect the storage. This is normal. Some object was created and then no longer referenced. When the heap gets full, the equivalent of `gc.collect()` will be called and the space for those non-referenced objects will be recovered.

This is similar to:
```py
import gc

while True:
    a = 'abc' + 'def'
    print(gc.mem_free())
```
You'll see storage decrease as the loop runs.

The string concatenation generates an object. When a new object is assigned to `a`, the old concatenated string is discarded.

"Regular" Python uses reference counting, so the storage is recovered immediately when the reference goes away. MicroPythong and CircuitPython don't use reference counting, but instead use a mark and sweep garbage collection scheme (and can't do compaction).
